---
- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Add Cilium Helm Repo
  shell: |
    helm repo add cilium https://helm.cilium.io/
    helm repo update
  changed_when: false

- name: Render Cilium Values
  copy:
    content: |
      l2announcements:
        enabled: true
      kubeProxyReplacement: true
      k8sServiceHost: "{{ ansible_host }}"
      k8sServicePort: 6443
      identityAllocationMode: crd
      encryption:
        enabled: true
        type: wireguard
      hubble:
        relay:
          enabled: true
        ui:
          enabled: true
    dest: /tmp/cilium-values.yaml

- name: Install Cilium via Helm CLI
  shell: |
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    helm upgrade --install cilium cilium/cilium --namespace kube-system --values /tmp/cilium-values.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
