---
caddy_sites:
  - domain: "xxx.xxx.com"
    upstream: ""
    host_header: "xxx.xxx.com"

xray_host_clients:
  - id: "xxxx"
    email: "temp-xxx"

tailscale_derp_enabled: false
tailscale_derp_hostname: ""
tailscale_enable_peer_relay: false
