---
# Skip entire role if no sites are configured
- name: Skip Caddy role if no sites configured
  meta: end_role
  when: caddy_sites | length == 0

- name: Install Caddy Prerequisites
  apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
    state: present
    update_cache: yes

- name: Add Caddy GPG Key
  shell: |
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

- name: Set GPG Key Permissions
  file:
    path: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    mode: 'o+r'

- name: Add Caddy Repository
  shell: |
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
  args:
    creates: /etc/apt/sources.list.d/caddy-stable.list

- name: Set Repository List Permissions
  file:
    path: /etc/apt/sources.list.d/caddy-stable.list
    mode: 'o+r'

- name: Update Apt Cache
  apt:
    update_cache: yes

- name: Install Caddy
  apt:
    name: caddy
    state: latest

- name: Create Caddy Config Directory
  file:
    path: /etc/caddy
    state: directory
    mode: '0755'

- name: data drive for caddy logs
  file:
    path: /var/log/caddy
    state: directory
    mode: '0755'
    owner: caddy
    group: caddy

- name: Configure Caddy
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: '0644'
  notify: Reload Caddy

- name: Ensure Caddy Service is Running
  service:
    name: caddy
    state: started
    enabled: yes
