---
admin_user: 

k3s_install_version: "v1.31.2+k3s1"

# --- Xray Configuration ---
xray_port_tcp: 
xray_private_key: "{{ vault_xray_private_key }}"

xray_clients:
  - id: "{{ vault_xray_u_admin }}"
    email: ""
    level: 0

  - id: "{{ vault_xray_u_partner }}"
    email: ""
    level: 0
