---
- import_tasks: hosts.yml
- import_tasks: dependencies.yml
- import_tasks: ntp.yml
- import_tasks: fail2ban.yml
- import_tasks: sshd.yml
- import_tasks: swap.yml
- import_tasks: tailscale.yml
- import_tasks: firewall.yml
